src/config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  devise_scope :admin do
    get "dashboard", :to => "dashboard#index"
    get "dashboard/login", :to => "admins/sessions#new"
    post "dashboard/login", :to => "admins/sessions#create"
    delete "dashboard/logout", :to => "admins/sessions#destroy"
  end

  namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :major_categories, except: [:new]
    resources :categories, except: [:new]
    resources :products, except: [:show] do
      collection do
        get  "import/csv", :to => "products#import"
        post "import/csv", :to => "products#import_csv"
        get  "import/csv_download", :to => "products#download_csv"
      end
    end
    resources :orders, only: [:index]
  end


  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }

  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end

  resource :users, only: [:edit, :update] do
    collection do
      get    "cart",               :to => "shopping_carts#index"
      delete "cart",               :to => "shopping_carts#destroy"
      post   "cart/create",        :to => "shopping_carts#create"
      get    "mypage",                 :to => "users#mypage"
      put    "mypage",                 :to => "users#update"
      get    "mypage/edit",            :to => "users#edit"
      get    "mypage/edit_password",   :to => "users#edit_password"
      delete "mypage/delete",          :to => "users#destroy"
      get    "mypage/address/edit",    :to => "users#edit_address"
      put    "mypage/password",        :to => "users#update_password"
      get    "mypage/favorite",        :to => "users#favorite"
      get    "mypage/cart_history",    :to => "users#cart_history_index", :as => "mypage_cart_histories"   
      get    "mypage/cart_history/:num", :to => "users#cart_history_show", :as => "mypage_cart_history"   
      get    "mypage/register_card",     :to => "users#register_card"
      post   "mypage/token",             :to => "users#token"
    end
  end

  resources :products do
    member do
      get :favorite
    end
    resources :reviews, only: [:create]
  end
end

src/app/views/layouts/_footer.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm fixed-bottom mt-5">
  <%= link_to root_path, class: "navbar-brand mx-auto" do %>
    <%= image_tag "/images/logo.jpg", class: "img-fuild" %>
  <% end %>
</nav>

src/app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm samuraimart-header-container">
    <%= link_to root_path do %>
      <%= image_tag "/images/logo.jpg" %>
    <% end %>
    <form class="form-inline">
      <div class="form-group">
        <input class="form-control samuraimart-header-search-input">
      </div>
      <div class="input-group">
        <button type="submit" class="btn samuraimart-header-search-button"><i class="fas fa-search samuraimart-header-search-icon"></i></button>
      </div>
    </form>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Right Side Of Navbar -->
      <ul class="navbar-nav ml-auto mr-5 mt-2">
      <!-- user_signed_in? はユーザがログインしているか調べるdeviseのHelperメソッド -->
      <% if user_signed_in? %>
        <li class="nav-item mr-5">
          <%= link_to mypage_users_path, class: "nav-link" do %>
            <i class="fas fa-user mr-1"></i><label>マイページ</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to mypage_favorite_users_path, class: "nav-link" do %>
            <i class="far fa-heart"></i>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to cart_users_path, class: "nav-link" do %>
            <i class="fas fa-shopping-cart"></i>
          <% end %>
        </li>
      <% else %>
        <li class="nav-item mr-5">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
            <label>新規登録</label>
          <% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %>
            <label>ログイン</label>
          <% end %>
        </li>
        <hr>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="far fa-heart"></i><% end %>
        </li>
        <li class="nav-item mr-5">
          <%= link_to login_path, class: "nav-link" do %><i class="fas fa-shopping-cart"></i><% end %>
        </li>
      <% end %>
    </div>
  </nav>
</header>

src/app/views/layouts/_sidebar.html.erb
<div class="container">
  <% major_category_names.each do |major_category_name| %>
    <h2><%= major_category_name %></h2>
    <% categories.each do |category| %>
      <% if category.major_category_name == major_category_name %>
        <label class="samuraimart-sidebar-category-label">
          <%= link_to category.name, products_path(category: category.id) %>
        </label>
      <% end %>
    <% end %>
  <% end %>
</div>

src/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= ENV["APP_NAME"] %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c63776209e.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render partial: 'layouts/header' %>
    <main class="py-4 mb-5">
      <% if notice %><p class="alert alert-warning"><%= notice %></div><% end %>
      <% if alert %><p class="alert alert-danger"><%= alert %></p><% end %>
      <%= yield %>
    </main>
    <%= render partial: 'layouts/footer' %>
  </body>
</html>